[build.targets.sdist]
ignore-vcs = true
include = [
  "/fdtd_fun",
]
exclude = [
  ".gitignore",
  "pyproject.toml",
  "hatch.toml"
]

[envs.test]
dependencies = ["pytest", "numpy"]
[envs.test.env-vars]
HATCH_INDEX_REPO = "test"
HATCH_BUILD_CLEAN = "true"

[envs.default.env-vars]
HATCH_INDEX_REPO = "main"
